import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider"
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/ChatSidebar"
import { ModeToggle } from "@/components/ModeToggle";


import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="overflow-hidden">
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <SidebarProvider>
              <div className="flex h-screen">
                <AppSidebar />
                <main className="flex-1 relative">
                  <div className="absolute z-50 flex items-center gap-4 m-4">
                  <div className="p-2 hover:bg-accent rounded-lg scale-125">
                    <SidebarTrigger />
                  </div>
                  <div className="p-2 hover:bg-accent rounded-lg scale-125">
                    <ModeToggle />
                  </div>
                  </div>
                  <div className="p-4">
                  {children}
                  </div>
                </main>
              </div>
            </SidebarProvider>
          </ThemeProvider>
      </body>
    </html>
  );
}
